### ISSUE TITLE
Cannot load such file

### ISSUE THREAD

**Issue by till** [andrewwardrobe/serverspec-extra-types#1]
Thanks for publishing these extra types. The Swarm related look very, very helpful and I wanted to use them in my test setup.

---

I followed the REAMDE and added your Gem to my `Gemfile`, ran `bundle` and included it in `spec_helper.rb`, but I receive the following error when I run `rake`

```
$ rake
/Users/till/.rbenv/versions/2.6.3/bin/ruby -I/Users/till/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.0/lib:/Users/till/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib /Users/till/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\{base,foo\}/\*_spec.rb

An error occurred while loading ./spec/foo/default_spec.rb.
Failure/Error: require 'serverspec-extra-types'

LoadError:
  cannot load such file -- serverspec-extra-types
# ./spec/spec_helper.rb:1:in `<top (required)>'
# ./spec/foo/default_spec.rb:1:in `<top (required)>'
```

**Comment by till** [comment]
For repro:

```
16:09 $ cat test.rb 
require 'serverspec-extra-types'
16:09 $ ruby test.rb 
Traceback (most recent call last):
	2: from test.rb:1:in `<main>'
	1: from /Users/till/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/till/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- serverspec-extra-types (LoadError)
```

Maybe this is fixed already, but not released?

**Comment by andrewwardrobe** [comment]
I'll look into this

**Comment by andrewwardrobe** [comment]
rwos has kindly provided a fix for this and it should be available as version 0.4.1.

Thank you for your patience

**Comment by till** [comment]
Thanks @rwos :D
